global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nextjs-app"
    static_configs:
      - targets: ["dugout-sandy.vercel.app:3000"]
    metrics_path: "/api/metrics" # Important: point to your metrics endpoint


  # - job_name: "socket"
  #   static_configs:
  #     - targets: ["dugout-socket-server.onrender.com:4000"]

  # - job_name: "mongo"
  #   static_configs:
  #     - targets: ["mongo:27017"]

  # - job_name: "redis"
  #   static_configs:
  #     - targets:
  #         ["redis-13217.c301.ap-south-1-1.ec2.redns.redis-cloud.com:6379"]
